---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: dev
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    tag: dev
  secretRef:
    name: flux-system
  url: ssh://git@github.com/stealthybox/flux-app-demo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: dev
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./config/play/apps-dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev
  validation: client
dependsOn:
  - name: infra
