---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: production
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    tag: production
  secretRef:
    name: flux-system
  url: ssh://git@github.com/stealthybox/flux-app-demo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: production
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./config/production/apps-production
  prune: true
  sourceRef:
    kind: GitRepository
    name: production
  validation: client
  dependsOn:
    - name: infra
